import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiTailwindcss,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiPrisma,
  SiGraphql,
  SiDocker,
  SiGit,
  SiGithub,
  SiPhp,
  SiBootstrap,
  SiVercel,
  SiNetlify,
  SiFramer,
  SiRedux,
  SiCodeigniter,
  SiHtml5,
  SiCss,
} from 'react-icons/si'

// Peta nama tech → icon component. Key harus lowercase.
const iconMap = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  'next.js': SiNextdotjs,
  nextjs: SiNextdotjs,
  'node.js': SiNodedotjs,
  nodejs: SiNodedotjs,
  express: SiExpress,
  'express.js': SiExpress,
  expressjs: SiExpress,
  tailwind: SiTailwindcss,
  'tailwind css': SiTailwindcss,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  prisma: SiPrisma,
  'prisma orm': SiPrisma,
  graphql: SiGraphql,
  docker: SiDocker,
  git: SiGit,
  'git & github': SiGithub,
  github: SiGithub,
  php: SiPhp,
  bootstrap: SiBootstrap,
  vercel: SiVercel,
  'vercel / netlify': SiVercel,
  netlify: SiNetlify,
  'framer motion': SiFramer,
  framer: SiFramer,
  redux: SiRedux,
  'redux / zustand': SiRedux,
  zustand: SiRedux,
  codeigniter: SiCodeigniter,
  'php / codeigniter': SiCodeigniter,
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss,
  css3: SiCss,
}

// Komponen icon tech stack. Menerima nama (case-insensitive).
export default function TechIcon({ name, size = 14, className = '' }) {
  const Icon = iconMap[name.toLowerCase()]
  if (!Icon) return null
  return <Icon size={size} className={className} />
}
